Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  config.vm.provision :chef_solo do |chef|
     chef.channel = "stable"
     chef.version = "12.10.24"
     chef.run_list = [
         "recipe[nginx]"
     ]
     end
end
